yarnPath: .yarn/releases/yarn-3.6.3.cjs
nodeLinker: node-modules

# Не прятать вывод во время install
enableInlineBuilds: true

# yarn install не запускает postinstall, если небыло изменения дерева зависимостей (https://github.com/yarnpkg/yarn/issues/5476).
# Фикс этого поведения через плагин https://github.com/mhassan1/yarn-plugin-after-install
afterInstall: yarn run license-checker --exclude axe-core

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js"
